baseURL = 'https://qishan233.github.io/'
languageCode = 'zh-cn'
title = "è½èŠ±æµæ°´å­˜å¿ƒé˜"
theme='github-style'
lastmod = true
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
  author = "QiShan"
  description = "éæ·¡æ³Šæ— ä»¥æ˜å¿—ï¼Œéå®é™æ— ä»¥è‡´è¿œ"
  github = "qishan233"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/favicon.png"
  avatar = "/images/avatar.jpg"
  headerIcon = "/images/header-icon.png"
  location = "China"